compiler = "gyc"
license = "GPL-v3"
authors = ["Emile Cadorel <ecadorel@gmail.com>"]
libraries = []
type = "executable"
description = "Ymir package manager, and builder"
version = "1.6.3"
name = "gyllir"
package-root = "main"

[std]
version = ["1.3.6"]
url = "git:https://github.com/GNU-Ymir/yruntime.git"

[dependencies]

[registry]
git = "git@github.com:GNU-Ymir/Gyllir.git"

[commands]
set-version = { cmd = "./tools/set-version.sh", post = false }
