compiler = "gyc"
license = "GPL-v3"
authors = ["Emile Cadorel <ecadorel@gmail.com>"]
libraries = []
type = "executable"
description = "Ymir package manager, and builder"
version = "1.8.0"
name = "gyllir"
package-root = "main"

[dependencies]

[registry]
git = "git@github.com:GNU-Ymir/Gyllir.git"

[commands]
set-version = { cmd = "./tools/set-version.sh", post = false }
